package com.example.dawproject.dao;

import com.example.dawproject.model.User;
import jakarta.persistence.*;
import jakarta.ejb.Stateless;
import java.util.List;

@Stateless
public class UserDAO {

    @PersistenceContext(unitName = "dawPU")
    private EntityManager em;

    public void addUser(User user) {
        em.persist(user);
    }

    public User findByUsernameAndPassword(String username, String password) {
        try {
            return em.createQuery(
                            "SELECT u FROM User u WHERE u.username = :username AND u.password = :password",
                            User.class
                    )
                    .setParameter("username", username)
                    .setParameter("password", password)
                    .getSingleResult();
        } catch (NoResultException e) {
            return null;
        }
    }

    public boolean exists(String username) {
        Long count = em.createQuery(
                        "SELECT COUNT(u) FROM User u WHERE u.username = :username",
                        Long.class
                )
                .setParameter("username", username)
                .getSingleResult();

        return count > 0;
    }

    public Long countUsers() {
        return em.createQuery("SELECT COUNT(u) FROM User u", Long.class)
                .getSingleResult();
    }

    public void createSchema() {
        em.createNativeQuery("""
        CREATE TABLE IF NOT EXISTS users (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            username VARCHAR(100) UNIQUE,
            password VARCHAR(100),
            email VARCHAR(150),
            role VARCHAR(30),
            bio VARCHAR(1000),
            profileImage VARCHAR(500)
        )
    """).executeUpdate();
    }


    public User updateUser(User user) {
        return em.merge(user);
    }

    public User findById(Long id) {
        return em.find(User.class, id);
    }

    public List<User> findAll() {
        return em.createQuery("SELECT u FROM User u", User.class).getResultList();
    }


    public void deleteByUser(User user) {
        em.createQuery("DELETE FROM Order o WHERE o.buyer.id = :userId OR o.seller.id = :userId")
                .setParameter("userId", user.getId())
                .executeUpdate();
    }

    public void deleteUser(User user) {
        User managedUser = em.merge(user);
        em.remove(managedUser);
    }
}